name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test-elixir-lt-1-11:
    runs-on: ubuntu-latest
    name: Test OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}

    strategy:
      matrix:
        otp: [21.x, 22.x, 23.x]
        elixir: [1.8.x, 1.9.x, 1.10.x]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-elixir@v1.5
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build/dev
            _build/test
          key: elixir-cache-${{secrets.CACHE_VERSION}}-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
          restore-keys: |
            elixir-cache-${{secrets.CACHE_VERSION}}-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-
            elixir-cache-${{secrets.CACHE_VERSION}}-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-

      - name: Install Dependencies
        run: mix deps.get

      - name: Test
        run: mix test

      - name: Dialyzer
        run: mix dialyzer --halt-exit-status
